---
abstract: 'String::Truncate filter for Template::Toolkit'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Module::Signature: 0
  Socket: 0
  Template::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-Filter-String-Truncate
recommends: {}
requires:
  String::Truncate: 0
  Template::Plugin::Filter: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Template-Plugin-Filter-String-Truncate
  homepage: http://search.cpan.org/dist/Template-Plugin-Filter-String-Truncate/
  repository: http://github.com/mschout/template-plugin-filter-string-truncate
version: 0.03
